name: CI
on:
  push:
  release:
    types: [ published ]
  pull_request:

jobs:
  ciJvms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'
      - name: sbt ci ${{ github.ref }}
        run: ./sbt ci

  ci:
    if: always()
    runs-on: ubuntu-latest
    needs: [ ciJvms ]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  publish:
    needs: ci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'sbt'
      - name: sbt +versionCheck ${{ github.ref }}
        run: ./sbt +versionCheck
      - name: sbt ci-release ${{ github.ref }}
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
          PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
